// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/AboutMarathon.tsx";
import * as $$$$$$1 from "./sections/ActionsAndVideo.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$5 from "./sections/Header.tsx";
import * as $$$$$$18 from "./sections/hero-1.tsx";
import * as $$$$$$19 from "./sections/hero-2.tsx";
import * as $$$$$$6 from "./sections/Hero.tsx";
import * as $$$$$$20 from "./sections/hero2.tsx";
import * as $$$$$$7 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$8 from "./sections/ImpactAndTestimonials.tsx";
import * as $$$$$$9 from "./sections/InterestForm.tsx";
import * as $$$$$$10 from "./sections/Logos.tsx";
import * as $$$$$$11 from "./sections/MediaAndAwards.tsx";
import * as $$$$$$12 from "./sections/Schedule.tsx";
import * as $$$$$$13 from "./sections/Sponsors.tsx";
import * as $$$$$$14 from "./sections/Testimonials.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";
import * as $$$$$$16 from "./sections/WhoCanParticipate.tsx";
import * as $$$$$$17 from "./sections/WhoMadeIt.tsx";

const manifest = {
  "sections": {
    "site/sections/AboutMarathon.tsx": $$$$$$0,
    "site/sections/ActionsAndVideo.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Footer.tsx": $$$$$$4,
    "site/sections/Header.tsx": $$$$$$5,
    "site/sections/hero-1.tsx": $$$$$$18,
    "site/sections/hero-2.tsx": $$$$$$19,
    "site/sections/Hero.tsx": $$$$$$6,
    "site/sections/hero2.tsx": $$$$$$20,
    "site/sections/ImageWithParagraph.tsx": $$$$$$7,
    "site/sections/ImpactAndTestimonials.tsx": $$$$$$8,
    "site/sections/InterestForm.tsx": $$$$$$9,
    "site/sections/Logos.tsx": $$$$$$10,
    "site/sections/MediaAndAwards.tsx": $$$$$$11,
    "site/sections/Schedule.tsx": $$$$$$12,
    "site/sections/Sponsors.tsx": $$$$$$13,
    "site/sections/Testimonials.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
    "site/sections/WhoCanParticipate.tsx": $$$$$$16,
    "site/sections/WhoMadeIt.tsx": $$$$$$17,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
